version: '3.8'
services:
  db:
    image: postgres:14
    container_name: board_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: board_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
